services:
    # backend:
    #     build:
    #         context: ./backend
    #         dockerfile: Dockerfile
    #     ports:
    #         - '8000:8000'
    #     env_file:
    #         - ./backend/.env
    #     volumes:
    #         - ./backend:/app
    #         - ai-models:/app/models
    #     depends_on:
    #         - minio
    #     networks:
    #         - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        env_file:
            - ./frontend/.env
            - ./frontend/.env.local
        volumes:
            - ./frontend:/app
        networks:
            - app-network

    # minio:
    #     image: minio/minio:latest
    #     ports:
    #         - '9000:9000'
    #         - '9001:9001'
    #     environment:
    #         - MINIO_ROOT_USER=admin
    #         - MINIO_ROOT_PASSWORD=abc@123A
    #     volumes:
    #         - minio-data:/data
    #     command: server /data --console-address ":9001"
    #     networks:
    #         - app-network

volumes:
    ai-models:
    minio-data:

networks:
    app-network:
        driver: bridge
