name: Deploy to VPS

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    deploy-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy Backend to VPS
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.SSH_SERVER_IP }} "
                  cd /root/kt-speakup
                  git pull origin main
                  source venv/bin/activate
                  pip install -r backend/requirements.txt
                  sudo systemctl restart ktspeakup
                  "

    deploy-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: frontend/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy Frontend to VPS #yêu cầu máy mạnh hơn
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.SSH_SERVER_IP }} "
                  cd /root/kt-speakup/frontend
                  if [ -f package-lock.json ]; then
                    npm ci --no-optional
                  else
                    npm install
                    npm ci --no-optional
                  fi
                  npm run build
                  sudo rsync -a --delete dist/ /var/www/kt-speakup/
                  sudo chown -R www-data:www-data /var/www/kt-speakup
                  sudo chmod -R 755 /var/www/kt-speakup
                  "

    restart-nginx:
        runs-on: ubuntu-latest
        needs: [deploy-backend, deploy-frontend]
        steps:
            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Restart Nginx
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.SSH_SERVER_IP }} "
                  sudo systemctl restart nginx
                  "
